### PR TITLE
Automatically regenerate skype token.

### PR DESCRIPTION
**Pull request by OttoHollmann**
As proposed in issue #5, adding commands `save-password` and `remove-password` to save user password into database. This password will be used to obtain new skype token when the previous one expires.

This is totally opt-in feature, so password will not be saved until user execute command `save-password`.

# Roadmap:
* [x] Add database column.
* [x] Add commands for storing and removing password.
* [x] Obtain new token when current one expires.
* [x] Automatically relogin upon bridge (re)start.

### CODE REVIEW

**Comment by nicodier** [comment]
Thanks, looking forward to see this feature! Actually I created a cron job that does a relogin every night (through matrix chat api) and removed the function to reset portals, because otherwise I always had to accept new portals after a logout/login.

**Comment by OttoHollmann** [comment]
I think I'm done with this pull request. Feel free to test it and provide feedback because I'm not using skype bridge so often.
You can also use my image for testing:
`docker pull registry.hollmann.cz/otto/public-docker:go-skype-bridge_Automatically_regenerate_skype_token`

Automatic relogin should work even without storing password into database. But if you want to be automatically logged in after bridge start, you have to store your password into database.

**Comment by pidongqianqian** [comment]
looks like a workaround.

my original idea was to refresh the new token from the old token to keep the login state, it was put on hold due to being busy with other things recently.

i'll start testing right away.

**Comment by pidongqianqian** [comment]
I reviewed the code and tested it.

there are two points:
1. the password needs to be encrypted before store, although the effect is limited, the risk of storing in plaintext is too great.
2. for users who log in by email, they cannot log in automatically after restarting the bridge because the characters in the id(xx:xxxxx) are not their valid usernames.

It would be nice if you could fix these, after that I'll merge this commit.

**Comment by pidongqianqian** [comment]
I reviewed the code and tested it.

there are two points:
1. the password needs to be encrypted before store, although the effect is limited, the risk of storing in plaintext is too great.
2. for users who log in by email, they cannot log in automatically after restarting the bridge because the characters in the id(xx:xxxxx) are not their valid usernames.

It would be nice if you could fix these, after that I'll merge this commit.

**Comment by forthommel** [comment]
Hello @pidongqianqian @OttoHollmann 
I was wondering if there was any update on this (at least for me :slightly_smiling_face:) long-awaited feature?

**Comment by pidongqianqian** [comment]
> Hello @pidongqianqian @OttoHollmann I was wondering if there was any update on this (at least for me 🙂) long-awaited feature?

I may have an update on it next week

**Comment by OttoHollmann** [comment]
Thank you for merging and apologies for delay.
But one feature is still missing - password encryption before storing it into database, I will try to come with another pull request within one week.

**Pull request merged**
